name: pf-weather # 
version: '0.1' # 
summary: This snap will display temperature in Pflugerville TX # 
description: This snap will display temperature in Pflugerville TX 
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:

 # This is the awk command
  awk:
    command: /usr/bin/awk
  sed:
    command: /bin/sed
  wget:
    command: /usr/bin/wget


 # This command runs the shell script to show system information
  gettemp:
    command: weather

  # This command runs the shell script to move the README to the user's home dir
  mvfile:
    command: copyreadme
    daemon: simple

parts:
  show:
    plugin: dump
    source: .
    stage-packages:
            - wget
            - sed
    build-packages:
            - wget
            - sed
